### PR TITLE
Updates composer dependencies

### PR DESCRIPTION
**Pull request by sbarbosa**
### What and why? 🤔

Updates the composer dependencies for the jetpack packages to the latest version. 

### Testing Steps ✍️

* Install this version of the plugin and test that it works fine. The easiest way to test is to create a temporary site and then connect the plugin to WPCOM.
* Run a smoke test of the Blaze Dashboard

### Review checklist
- [x] Run `pnpm changelog` to add a changelog file, choose `patch` to leave it empty if the change is not significant. You can add multiple changelog files in one PR by running this command a few times.
- [ ] New tests have been added

### CODE REVIEW

**Review by timur987 — APPROVED** [review]
Thanks @sbarbosa!

Overall change looks great and I was able to create an Ad Campaign on Jurassic Ninja site using the plugin.

I noticed that the change does not bump up the plugin's version (is it intentional?), so it's still 0.5.2. Rather that that, everything works as expected.

**Comment by sbarbosa** [comment]
Hi @timur987!

> I noticed that the change does not bump up the plugin's version (is it intentional?), so it's still 0.5.2. Rather that that, everything works as expected.

Yes, this is correct. The plugin is released in a separate PR using a couple of Github workflows. You can check the PR for the latest release here: https://github.com/Automattic/blaze-ads/pull/54

**Comment by timur987** [comment]
> Hi @timur987!
> 
> > I noticed that the change does not bump up the plugin's version (is it intentional?), so it's still 0.5.2. Rather that that, everything works as expected.
> 
> Yes, this is correct. The plugin is released in a separate PR using a couple of Github workflows. You can check the PR for the latest release here: #54

Maybe I got something wrong, but the released plugin is already on WP.ORG (https://wordpress.org/plugins/blaze-ads/) and he's already had 0.5.2. That's why I though that this version should increment a minor version. But, I don't know the exact approach to versions. So please take it with a grain of salt 🧂 .

**Comment by sbarbosa** [comment]
> Maybe I got something wrong, but the released plugin is already on WP.ORG (https://wordpress.org/plugins/blaze-ads/) and he's already had 0.5.2. That's why I though that this version should increment a minor version. But, I don't know the exact approach to versions. So please take it with a grain of salt 🧂 .

We still need to generate the version in GitHub before we release it to dotorg. The plugin's field guide page explains the deployment process and then publishes the new version to dotorg: PCYsg-XnJ-p2

The main idea of the process for this repo is:
1- Merge all of the PR directly to trunk until we are ready to make a release
2- Release the plugin version in Git Hub following the steps explained in the previous guide. In summary, this will create a PR that will change the version number and changelog, and then create a new release in github
3- Take the tag generated in the release to push the next version to dotorg.

I haven't release to dotorg yet, but I just noticed that James added the section in the same guide.

**Pull request merged**
